### ISSUE TITLE
Integration don't work since 48897

### ISSUE THREAD

**Issue by Christianbouchard2** [eelcohn/home-assistant-ddwrt#18]
Hi, I update my router this week and the new firmware don't work with the integration. I try all the version(17) between the 48897 and the newest version. I don't know why it don't work. The error message don't talk really. If you are able to correct the problem, it would be very appreciated. I love this integration into homeassistant. Thank you!

**Comment by eelcohn** [comment]
Can you post some debug logging here, so I can see what's failing?

**Comment by Christianbouchard2** [comment]
Thank to reply, I updated for the latest version this week and nothing work. Here are the logs:
Logger: homeassistant.config_entries
Source: custom_components/ddwrt/pyddwrt.py:353
Integration: DD-WRT
First occurred: 08:53:53 (1 occurrences)
Last logged: 08:53:53

Error setting up entry 192.168.0.1 (configuration.yaml) for ddwrt
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/ddwrt/__init__.py", line 191, in async_setup_entry
    if not await router.async_update_sensor_data():
  File "/config/custom_components/ddwrt/__init__.py", line 382, in async_update_sensor_data
    result = await self._hass.async_add_executor_job(self._router.update_wireless_data)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/ddwrt/pyddwrt.py", line 353, in update_wireless_data
    self.results.update({"wl_radio": True if self.data.pop("wl_radio").strip().split(" ")[2]  == "On" else False})
IndexError: list index out of range

I hope you will find something, I liked this home assistant addon

**Comment by eelcohn** [comment]
I've updated the code to show a more user-friendly error, and to improve invalid wireless radio values. Can you update your code and recheck?

**Comment by Christianbouchard2** [comment]
Everything is working fine, thank you very much. One last question, does the reboot service work? If yes, how should it be configured? So far it's not working on my side.

**Comment by eelcohn** [comment]
Glad to hear that it's working again. You'll probably find the following error message in your Home Assistant log:
```Unknown wireless radio status, please report this to the author: ....```
Can you check if it's there and post that error message here?

As for the reboot service not working: I've opened a seperate issue for that, see #21
